name: Test

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      if: github.event.action == 'deploy'
      run: |
        echo "OK"
        cat $GITHUB_EVENT_PATH
    - name: test2
      if: github.event.action == 'deploy2'
      run: |
        echo "OK2"
        cat $GITHUB_EVENT_PATH
