name: Test

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - if: github.event.action.startsWith('deploy')
    - name: test
      run: |
        echo "OK"
        cat $GITHUB_EVENT_PATH
