name: Test

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      if: github.event.action == 'deploy'
      run: |
        echo "OK"
        cat $GITHUB_EVENT_PATH
